"""init_db

Revision ID: 001cfd5385f4
Revises: 
Create Date: 2026-01-14 10:05:24.315357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001cfd5385f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('integration_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('connected_account_id', sa.String(), nullable=True),
    sa.Column('connection_details', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_metadata_id'), 'integration_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_integration_metadata_integration_id'), 'integration_metadata', ['integration_id'], unique=False)
    op.create_index(op.f('ix_integration_metadata_user_id'), 'integration_metadata', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_metadata_user_id'), table_name='integration_metadata')
    op.drop_index(op.f('ix_integration_metadata_integration_id'), table_name='integration_metadata')
    op.drop_index(op.f('ix_integration_metadata_id'), table_name='integration_metadata')
    op.drop_table('integration_metadata')
    # ### end Alembic commands ###
